; ReallySmartHouse � gateway
; Owner: Giacomo Visintin (s253622)
[env:esp32]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 57600
upload_port = COM14
monitor_port = COM14
board_build.partitions = huge_app.csv
lib_deps = blynkkk/Blynk@^1.3.2
