; ReallySmartHouse — gateway
; Owner: Giacomo Visintin (s253622)
[env:gateway]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    sandeepmistry/LoRa
    blynkkk/Blynk
lib_extra_dirs = ../shared
build_flags =
    -DNODE_OWNER='\"Giacomo Visintin\"'
    -DSTUDENT_ID='\"s253622\"'
