; ReallySmartHouse — aquarium
; Owner: Nicol Costas (s253623)
[env:aquarium]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    sandeepmistry/LoRa
    milesburton/DallasTemperature
    blynkkk/Blynk
lib_extra_dirs = ../shared
build_flags =
    -DNODE_OWNER='\"Nicol Costas\"'
    -DSTUDENT_ID='\"s253623\"'
