; ReallySmartHouse plant-node
; Owner: Simone Panella (s253125)
[env:plant_node]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 57600
upload_port = COM3
monitor_port = COM3
lib_deps =
    sandeepmistry/LoRa
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
lib_extra_dirs = ../shared
build_flags =
    -DNODE_OWNER='\"Simone_Panella\"'
    -DSTUDENT_ID='\"s253125\"'
