; ReallySmartHouse plant-node
; Owner: Simone Panella (s253125)
[env:esp32]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 57600
board_build.partitions = default.csv
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14