; ReallySmartHouse — pet-tracker
; Owner: Sofía Da Silva (s253625)
[env:pet_tracker]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    sandeepmistry/LoRa
    mikalhart/TinyGPSPlus
    ESP32 BLE Arduino
lib_extra_dirs = ../shared
build_flags =
    -DNODE_OWNER='\"Sofía Da Silva\"'
    -DSTUDENT_ID='\"s253625\"'
