[env:pet_tracker]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM9
monitor_port = COM9

lib_deps =
    ESP32 BLE Arduino
    https://github.com/jpmeijers/RN2483-Arduino-Library