; ReallySmartHouse — mailbox
; Owner: Ignacio Díez (s253632)
[env:mailbox]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    sandeepmistry/LoRa
    bogde/HX711
lib_extra_dirs = ../shared
build_flags =
    -DNODE_OWNER='\"Ignacio Díez\"'
    -DSTUDENT_ID='\"s253632\"'
